#!/bin/bash

set -e # Fail on any error

mkdir dist lib third_party
git remote rm origin
echo "# $PACKAGE_NAME" > README.md
npm init
PACKAGE_NAME=$(node -p "require('$(npm prefix)/package.json').name")
YEAR=$(date +%Y)
sed -i '' "s/PACKAGE_NAME/${PACKAGE_NAME}/g" package.json
sed -i '' "s/YEAR/${YEAR}/g" LICENSE index.js
git mv test/test-NAME.js test/test-${PACKAGE_NAME}.js
npm install

git rm scripts/init-repo
git reset --soft ceac6c && git add . && git commit --no-verify --amend -m 'Initial commit.'
